network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: xx:xx:xx:xx:xx:xx
      addresses:
        - x.x.x.x/nn
        #- 2a02:c205:2027:0003:0000:0000:0000:0001/64
      #gateway6: fe80::1
      routes:
        - to: 0.0.0.0/0
          via: x.x.x.x
          on-link: true
      nameservers:
        search: [ invalid ]
        addresses:
          - x.x.x.x
          #- 2a02:c205::2:53
          #- 2a02:c205::1:53
